import{a as y,i as l,S as f}from"./assets/vendor-89feecc5.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function c(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=c(e);fetch(e.href,r)}})();y.defaults.baseURL="https://pixabay.com/";const v=document.querySelector(".search-form"),u=document.querySelector(".gallery"),m=document.querySelector(".loader"),n=document.querySelector(".load-more");let d="",a=1;v.addEventListener("submit",w);function w(o){o.preventDefault(),a=1,d=o.target.elements.searchQuery.value.trim(),m.style.display="block",p(d).then(t=>{if(t.hits.length===0)return u.innerHTML="",n.style.display="none",l.warning({title:"Wrong request",message:"Sorry, there are no images matching your search query. Please try again!"});u.innerHTML=g(t.hits),m.style.display="none",n.style.display="block",new f(".gallery a"),t.totalHits<=a*40&&(l.success({title:"That's all",message:"Try another word"}),n.style.display="none")}).catch(t=>l.error({title:"Error",message:`Oh, we have problem: ${t}`})),o.target.elements.searchQuery.value=""}n.addEventListener("click",L);function L(){a+=1,p(d).then(o=>{if(u.insertAdjacentHTML("beforeend",g(o.hits)),o.totalHits<=a*40){l.warning({title:"Try another word",message:"We're sorry, but you've reached the end of search results."}),n.style.display="none";return}new f(".gallery a");const t=document.querySelector(".gallery__link").getBoundingClientRect();window.scrollBy({top:t.height*2,behavior:"smooth"})})}async function p(o){return(await y.get("api/",{params:{key:"41293253-42a55b268bdac57d89d3cc200",q:o,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:40,page:a}})).data}function g(o){return o.map(({webformatURL:t,largeImageURL:c,tags:i,likes:e,views:r,comments:s,downloads:h,id:b})=>`<a class="gallery__link" href="${c}">
  <div class="gallery-item" id="${b}">
    <img class="gallery-item__img" src="${t}" alt="${i}" loading="lazy">
    <div class="info">
      <p class="info-item"><b>Likes</b>${e}</p>
      <p class="info-item"><b>Views</b>${r}</p>
      <p class="info-item"><b>Comments</b>${s}</p>
      <p class="info-item"><b>Downloads</b>${h}</p>
    </div>
  </div>
</a>`).join("")}
//# sourceMappingURL=commonHelpers.js.map
